"""User modeliga refresh_token qo'shildi

Revision ID: 81d2b6844d7d
Revises: c4667d49008a
Create Date: 2025-03-19 11:21:18.604047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81d2b6844d7d'
down_revision: Union[str, None] = 'c4667d49008a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article_banner', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'article_media', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'article_saved', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'article_saved', 'tg_users', ['tg_user_id'], ['user_id'])
    op.create_foreign_key(None, 'article_views', 'tg_users', ['tg_user_id'], ['user_id'])
    op.create_foreign_key(None, 'article_views', 'articles', ['article_id'], ['id'])
    op.drop_constraint('articles_ibfk_3', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'region', ['region_id'], ['id'])
    op.alter_column('queue', 'send_chat_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'queue', 'articles', ['article_id'], ['id'])
    op.create_foreign_key(None, 'queue', 'region', ['region_id'], ['id'])
    op.create_foreign_key(None, 'tg_users', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_constraint(None, 'tg_users', type_='foreignkey')
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.alter_column('queue', 'send_chat_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_ibfk_3', 'articles', 'users', ['region_id'], ['id'])
    op.drop_constraint(None, 'article_views', type_='foreignkey')
    op.drop_constraint(None, 'article_views', type_='foreignkey')
    op.drop_constraint(None, 'article_saved', type_='foreignkey')
    op.drop_constraint(None, 'article_saved', type_='foreignkey')
    op.drop_constraint(None, 'article_media', type_='foreignkey')
    op.drop_constraint(None, 'article_banner', type_='foreignkey')
    # ### end Alembic commands ###
